# Generated by Django 4.1 on 2023-10-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_companyprofile_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
