# Generated by Django 4.1 on 2023-10-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_alter_customuser_email_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.CharField(max_length=500),
        ),
    ]
