# Generated by Django 4.1 on 2023-10-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_alter_jobapplication_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='aggregate_cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='class_10th_board',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='class_10th_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='class_12th_board',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='class_12th_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
    ]
